In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt

In [3]:
dataframe_train = pd.read_csv('train.csv')
dataframe_train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [4]:
dataframe_train.shape

(891, 12)

In [5]:
dataframe_train.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
dataframe_train.Cabin.unique()

array([nan, 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6',
       'C23 C25 C27', 'B78', 'D33', 'B30', 'C52', 'B28', 'C83', 'F33',
       'F G73', 'E31', 'A5', 'D10 D12', 'D26', 'C110', 'B58 B60', 'E101',
       'F E69', 'D47', 'B86', 'F2', 'C2', 'E33', 'B19', 'A7', 'C49', 'F4',
       'A32', 'B4', 'B80', 'A31', 'D36', 'D15', 'C93', 'C78', 'D35',
       'C87', 'B77', 'E67', 'B94', 'C125', 'C99', 'C118', 'D7', 'A19',
       'B49', 'D', 'C22 C26', 'C106', 'C65', 'E36', 'C54',
       'B57 B59 B63 B66', 'C7', 'E34', 'C32', 'B18', 'C124', 'C91', 'E40',
       'T', 'C128', 'D37', 'B35', 'E50', 'C82', 'B96 B98', 'E10', 'E44',
       'A34', 'C104', 'C111', 'C92', 'E38', 'D21', 'E12', 'E63', 'A14',
       'B37', 'C30', 'D20', 'B79', 'E25', 'D46', 'B73', 'C95', 'B38',
       'B39', 'B22', 'C86', 'C70', 'A16', 'C101', 'C68', 'A10', 'E68',
       'B41', 'A20', 'D19', 'D50', 'D9', 'A23', 'B50', 'A26', 'D48',
       'E58', 'C126', 'B71', 'B51 B53 B55', 'D49', 'B5', 'B20', 'F G63',
       'C62 C64',

In [7]:
dataframe_train.Survived.value_counts()

0    549
1    342
Name: Survived, dtype: int64

In [8]:
dataframe_train.Sex.value_counts()

male      577
female    314
Name: Sex, dtype: int64

In [9]:
dataframe_train.Embarked.value_counts()

S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [10]:
dataframe_train.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [11]:
dataframe_train.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [12]:
# All these columns seems to be irrelevant. Though you can add SibSp and Parch in your data.
columns_to_drop = ['PassengerId', 'Name', 'SibSp', 'Parch', 'Ticket', 'Cabin','Embarked']

In [13]:
dataframe_train = dataframe_train.drop(columns_to_drop, axis = 1)
dataframe_train.head()

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [14]:
dataframe_train[dataframe_train['Age'].isna()]

Survived  Pclass     Sex  Age     Fare
5           0       3    male  NaN   8.4583
17          1       2    male  NaN  13.0000
19          1       3  female  NaN   7.2250
26          0       3    male  NaN   7.2250
28          1       3  female  NaN   7.8792
..        ...     ...     ...  ...      ...
859         0       3    male  NaN   7.2292
863         0       3  female  NaN  69.5500
868         0       3    male  NaN   9.5000
878         0       3    male  NaN   7.8958
888         0       3  female  NaN  23.4500

[177 rows x 5 columns]

In [59]:
# Smart way of replacing null values in age column by looking into Pclass as reference column
dataframe_train.groupby('Pclass').mean()[['Age']]

Age
Pclass           
1       38.233441
2       29.877630
3       25.140620

In [15]:
def age_approx(cols):
    Age = cols[0]
    Pclass = cols[1]
    
    if pd.isnull(Age):
        if Pclass == 1 :
            return 39
        elif Pclass == 2:
            return 30
        else:
            return 24
    else:
        return Age

In [16]:
dataframe_train['Age'] = dataframe_train[['Age','Pclass']].apply(age_approx, axis = 1)
dataframe_train.head(10)

Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500
5         0       3    male  24.0   8.4583
6         0       1    male  54.0  51.8625
7         0       3    male   2.0  21.0750
8         1       3  female  27.0  11.1333
9         1       2  female  14.0  30.0708

In [17]:
dataframe_train.isna().sum()

Survived    0
Pclass      0
Sex         0
Age         0
Fare        0
dtype: int64

In [18]:
dataframe_train.dtypes

Survived      int64
Pclass        int64
Sex          object
Age         float64
Fare        float64
dtype: object

In [19]:
# Sex column is a Nominal variable so applying one hot encoding
dataframe_train_one_hot = pd.get_dummies(dataframe_train, columns = ['Sex'])

In [20]:
dataframe_train_one_hot

Survived  Pclass   Age     Fare  Sex_female  Sex_male
0           0       3  22.0   7.2500           0         1
1           1       1  38.0  71.2833           1         0
2           1       3  26.0   7.9250           1         0
3           1       1  35.0  53.1000           1         0
4           0       3  35.0   8.0500           0         1
..        ...     ...   ...      ...         ...       ...
886         0       2  27.0  13.0000           0         1
887         1       1  19.0  30.0000           1         0
888         0       3  24.0  23.4500           1         0
889         1       1  26.0  30.0000           0         1
890         0       3  32.0   7.7500           0         1

[891 rows x 6 columns]

In [21]:
dataframe_train_one_hot.columns

Index(['Survived', 'Pclass', 'Age', 'Fare', 'Sex_female', 'Sex_male'], dtype='object')

In [22]:
X = dataframe_train_one_hot[['Pclass', 'Age', 'Fare', 'Sex_female', 'Sex_male']]
y = dataframe_train_one_hot['Survived']

In [23]:
X.shape,y.shape

((891, 5), (891,))

In [24]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

In [25]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((668, 5), (223, 5), (668,), (223,))

In [28]:
# from sklearn.preprocessing import StandardScaler, MinMaxScaler

# age_mm_scaler = MinMaxScaler()
# fare_std_scaler = StandardScaler()

# # X_train['Age'] = age_mm_scaler.fit_transform(X_train[['Age']])
# X_train['Fare'] = fare_std_scaler.fit_transform(X_train[['Fare']])
# X_train

Pclass   Age      Fare  Sex_female  Sex_male
852       3   9.0 -0.338475           1         0
230       1  35.0  1.107975           1         0
90        3  29.0 -0.491025           0         1
20        2  35.0 -0.110487           0         1
475       1  39.0  0.440709           0         1
..      ...   ...       ...         ...       ...
458       2  50.0 -0.439085           1         0
381       3   1.0 -0.327962           1         0
507       1  39.0 -0.098827           0         1
154       3  24.0 -0.506660           0         1
470       3  24.0 -0.507985           0         1

[668 rows x 5 columns]

In [26]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [27]:
logreg.fit(X_train,y_train)

LogisticRegression()

In [28]:
logreg.coef_, logreg.intercept_

(array([[-1.25660329, -0.03774175, -0.0026154 ,  1.25255716, -1.25220993]]),
 array([3.83038666]))

In [33]:
# X_test['Fare'] = fare_std_scaler.transform(X_test[['Fare']])

In [29]:
y_pred = logreg.predict(X_test)
y_pred

array([0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0,
       0, 0, 0])

In [30]:
[logreg.predict_proba(X_test)[i] for i in range(len(X_test))]

[array([0.89964202, 0.10035798]),
 array([0.2355859, 0.7644141]),
 array([0.89248145, 0.10751855]),
 array([0.3692017, 0.6307983]),
 array([0.46462389, 0.53537611]),
 array([0.75050033, 0.24949967]),
 array([0.58685454, 0.41314546]),
 array([0.40441674, 0.59558326]),
 array([0.79852068, 0.20147932]),
 array([0.88181175, 0.11818825]),
 array([0.90947141, 0.09052859]),
 array([0.74407975, 0.25592025]),
 array([0.89600614, 0.10399386]),
 array([0.25127983, 0.74872017]),
 array([0.89264863, 0.10735137]),
 array([0.71352654, 0.28647346]),
 array([0.75050033, 0.24949967]),
 array([0.1012946, 0.8987054]),
 array([0.74211726, 0.25788274]),
 array([0.70101211, 0.29898789]),
 array([0.53806337, 0.46193663]),
 array([0.89250236, 0.10749764]),
 array([0.20059794, 0.79940206]),
 array([0.799088, 0.200912]),
 array([0.72013379, 0.27986621]),
 array([0.09901551, 0.90098449]),
 array([0.56018027, 0.43981973]),
 array([0.89453961, 0.10546039]),
 array([0.85528477, 0.14471523]),
 array([0.11628462, 0.88

In [35]:
# Prediciting Probabilities
# [np.argmax(logreg.predict_proba(X_test)[i]) for i in range(len(X_test))]

In [35]:
from sklearn import metrics

In [36]:
metrics.accuracy_score(y_test, y_pred)

0.7982062780269058

In [37]:
metrics.confusion_matrix(y_test, y_pred)

array([[112,  21],
       [ 24,  66]])

In [38]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.82      0.84      0.83       133
           1       0.76      0.73      0.75        90

    accuracy                           0.80       223
   macro avg       0.79      0.79      0.79       223
weighted avg       0.80      0.80      0.80       223

